### ISSUE TITLE
Some final comments

### ISSUE THREAD

**Issue by caredg** [cms-opendata-workshop/workshop-lesson-docker-preexercises#10]
Thanks @mattbellis  for the nice lesson.  I actually learned a few things myself.  I have some comments:

- [x]  [Here](https://github.com/cms-opendata-workshop/workshop-lesson-docker-preexercises/blame/gh-pages/index.md#L18) maybe we want to link to [mattermost](https://mattermost.web.cern.ch/cmsopendatatheo/channels/town-square)? Likewise [here](https://github.com/cms-opendata-workshop/workshop-lesson-docker-preexercises/blame/gh-pages/_episodes/03-testing-docker-for-cms-opendata.md#L22) and probably other instances.
- [x] Introduction takes much less than 10 min I believe.  Took me 2 min, maybe 5 would be ok
- [x] I generally when it is too much detail, but [here](https://github.com/cms-opendata-workshop/workshop-lesson-docker-preexercises/blame/gh-pages/_episodes/03-testing-docker-for-cms-opendata.md#L89) maybe it would be good to clarify that those paths could be different in different systems.  Also, it is safe to ignore the ssh stuff if they don't feel comfortable with that.
- [x] Actually, funny names are given automatically, I presume `docker start -i happy_greider` will do as well.
- [x] Actually [here](https://github.com/cms-opendata-workshop/workshop-lesson-docker-preexercises/blame/gh-pages/_episodes/03-testing-docker-for-cms-opendata.md#L253) it does not really matter whether they have mounted the .ssh volume or not.  That is useful mostly for pushing to the repo but for cloning it does not really matter I believe.  Only the use of the prefix `git` instead of `https` does due to the older version in the container.
- [x] For [this challenge](https://github.com/cms-opendata-workshop/workshop-lesson-docker-preexercises/blame/gh-pages/_episodes/03-testing-docker-for-cms-opendata.md#L265), however, you do need the .ssh thing.  However, cloning and pushing are really disjoint.  Wouldn't it be appropiate to put a little note here saying that "If you are confident with git and github..."  
- [x] Without the waiting for the image download, the Using Docker with the CMS open data episode takes like 15 min.  Should we maybe shorten the declared time from 60 min to maybe 40?  I do not want to scare people too much before the workshop ;) (I am trying to reduce the total, which is now close to 4h!)
- [x] Actually, [here](https://github.com/cms-opendata-workshop/workshop-lesson-docker-preexercises/blame/gh-pages/_episodes/04-cvmfs-and-brilcalc.md#L2), cvmfs will not only be used for luminosity but for accessing the conditions data for trigger stuff (maybe even data scouting), for jet corrections, and root.
- [x] Could we also say that the CVMFS will last a bit less time?  Maybe not 1h but 40 min (I believe is realistic). Maybe we could even drop the brilcalc installation (Tom will cover that for sure, see below)
- [x] If kept, it's maybe worth mentioning [here](https://github.com/cms-opendata-workshop/workshop-lesson-docker-preexercises/blame/gh-pages/_episodes/04-cvmfs-and-brilcalc.md#L131) that there will be a full session (demo) on this luminosity topic with a soothing [Bob Ross-like voice](https://twitter.com/tpmccauley/status/1308477879324487680) :)
- [x] The validation lesson still has a lot of references to VMs right? It needs cleaning I think, including #9 
- [x] On Docker, it is possible that cvmfs actuall does not [expand](https://github.com/cms-opendata-workshop/workshop-lesson-docker-preexercises/blame/gh-pages/_episodes/05-validation.md#L149).  One way I found for fixing this is to go to the local machine, where the actual /cvmfs volume is, and do the `cvmfs_config probe`.  This needs to be done every time I open the container (maybe I am doing something wrong, but it could be worth mentioning).
- [x] Ok for the validation episode, I timed myself and it took me 20 min.  I think  for the VM it will be a bit more, but I will reduce the time for that lesson as well.  It won't take more than 40 min in total.  I think the current time is too much.

**Comment by mattbellis** [comment]
I'll check off what I've done and comment here when I've done it or not done it and what my point of view is. 

* Mattermost links. Good catch. Done. 

* Time estimate. I'm going to keep 10 min. I think we forget what it's like for new users who might spend more time reading the links. They don't know what's important and what's not so I estimated based on that. If it's shorter, it's OK. 

* Added comments about the ssh paths and option to ignore

* Yeah, the funny names are there but the if the user wants to return to the same instance everytime they do work, they should give it a name. 

* True about the ssh keys being needed for pushing and not for cloning. When I first put these instructions together, we had been talking about users cloning a whole set of lessons in one go and building upon them. I had assumed (maybe incorrectly) that users would use their own branches or their own repos, so that they could keep their work. I'm not sure how users develop their analysis workflow if they're not using some sort of external version control. 

* Good point about the "If you are confident with git..." Added. 

* Changed time from 60 min to 40 min

* Changed lesson title to be "Setting up CVMFS"

* Changed CVMFS time to 45 min total. I think we want them to do the brilcalc stuff in advance. It takes a while to get it running that first time and we don't want them just spinning their wheels. TBH, once CVMFS is set up, the brilcalc stuff is pretty quick, modulo the time it takes that first time. 

* Added text mentioning brilcalc exercise. 

* Cleaned up the VM references in the Validation lesson. 

* Added some text about the probe issue with CVMFS. I'm finding that with mine as well. 

* Changed the total validation time to 40 min.
